"""schema_v2_metrics_and_ui

Revision ID: 96703fb6b631
Revises: 
Create Date: 2026-03-08 07:45:28.246684

"""
from typing import Sequence, Union

from alembic import op  # type: ignore[attr-defined]
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96703fb6b631'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('sub_title', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('event_image_url', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('featured_image_url', sa.Text(), nullable=True))
    op.add_column('events', sa.Column('settlement_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('events', sa.Column('competition', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('competition_scope', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('total_volume', sa.Numeric(precision=24, scale=8), nullable=True))
    op.add_column('events', sa.Column('open_interest', sa.Numeric(precision=24, scale=8), nullable=True))
    op.add_column('markets', sa.Column('yes_sub_title', sa.Text(), nullable=True))
    op.add_column('markets', sa.Column('no_sub_title', sa.Text(), nullable=True))
    op.add_column('markets', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('markets', sa.Column('color_code', sa.String(length=10), nullable=True))
    op.add_column('markets', sa.Column('fractional_trading_enabled', sa.Boolean(), nullable=True))
    op.add_column('markets', sa.Column('response_price_units', sa.String(length=50), nullable=True))
    op.add_column('markets', sa.Column('strike_type', sa.String(length=50), nullable=True))
    op.add_column('markets', sa.Column('open_interest', sa.Numeric(precision=24, scale=8), nullable=True))
    op.add_column('markets', sa.Column('volume', sa.Numeric(precision=24, scale=8), nullable=True))
    op.add_column('markets', sa.Column('volume_24h', sa.Numeric(precision=24, scale=8), nullable=True))
    op.add_column('markets', sa.Column('total_volume', sa.Numeric(precision=24, scale=8), nullable=True))
    op.add_column('markets', sa.Column('liquidity', sa.Numeric(precision=24, scale=8), nullable=True))
    op.add_column('series', sa.Column('settlement_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('series', sa.Column('contract_url', sa.Text(), nullable=True))
    op.add_column('series', sa.Column('additional_prohibitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('series', sa.Column('fee_type', sa.String(length=50), nullable=True))
    op.add_column('series', sa.Column('fee_multiplier', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('series', sa.Column('volume_24h', sa.Numeric(precision=24, scale=8), nullable=True))
    op.add_column('series', sa.Column('total_volume', sa.Numeric(precision=24, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'total_volume')
    op.drop_column('series', 'volume_24h')
    op.drop_column('series', 'fee_multiplier')
    op.drop_column('series', 'fee_type')
    op.drop_column('series', 'additional_prohibitions')
    op.drop_column('series', 'contract_url')
    op.drop_column('series', 'settlement_sources')
    op.drop_column('markets', 'liquidity')
    op.drop_column('markets', 'total_volume')
    op.drop_column('markets', 'volume_24h')
    op.drop_column('markets', 'volume')
    op.drop_column('markets', 'open_interest')
    op.drop_column('markets', 'strike_type')
    op.drop_column('markets', 'response_price_units')
    op.drop_column('markets', 'fractional_trading_enabled')
    op.drop_column('markets', 'color_code')
    op.drop_column('markets', 'image_url')
    op.drop_column('markets', 'no_sub_title')
    op.drop_column('markets', 'yes_sub_title')
    op.drop_column('events', 'open_interest')
    op.drop_column('events', 'total_volume')
    op.drop_column('events', 'competition_scope')
    op.drop_column('events', 'competition')
    op.drop_column('events', 'settlement_sources')
    op.drop_column('events', 'featured_image_url')
    op.drop_column('events', 'event_image_url')
    op.drop_column('events', 'sub_title')
    # ### end Alembic commands ###
