"""array_taxonomy

Revision ID: e649bafc2cfa
Revises: 
Create Date: 2026-03-13 00:50:20.053209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e649bafc2cfa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema: array taxonomy columns + platform_tags table; drop legacy category/tag tables."""

    # --- Drop legacy Category and Tag tables (replaced by PlatformTag) ---
    op.execute("DROP TABLE IF EXISTS categories CASCADE")
    op.execute("DROP TABLE IF EXISTS tags CASCADE")

    # --- Create platform_tag_type enum ---
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE platform_tag_type AS ENUM ('category', 'tag');
        EXCEPTION WHEN duplicate_object THEN NULL;
        END $$;
    """)

    # --- Create platform_tags table (idempotent) ---
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()
    if 'platform_tags' not in existing_tables:
        op.create_table(
            'platform_tags',
            sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True,
                      server_default=sa.text('gen_random_uuid()')),
            sa.Column('exchange', postgresql.ENUM('kalshi', 'polymarket',
                                                  name='exchange_type',
                                                  create_type=False), nullable=False),
            sa.Column('type', postgresql.ENUM('category', 'tag',
                                              name='platform_tag_type',
                                              create_type=False), nullable=False),
            sa.Column('ext_id', sa.String(), nullable=False),
            sa.Column('parent_id', sa.String(), nullable=True),
            sa.Column('slug', sa.String(), nullable=False),
            sa.Column('label', sa.String(), nullable=False),
            sa.Column('image_url', sa.Text(), nullable=True),
            sa.Column('is_carousel', sa.Boolean(), server_default='false', nullable=False),
            sa.Column('force_show', sa.Boolean(), server_default='false', nullable=False),
            sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()')),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()')),
            sa.UniqueConstraint('exchange', 'slug', 'type', name='uq_platform_tags_exchange_slug_type'),
        )
        op.create_index('idx_platform_tags_slug', 'platform_tags', ['slug'])
        op.create_index('idx_platform_tags_exchange_type', 'platform_tags', ['exchange', 'type'])

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('events', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('events', sa.Column('series_ids', postgresql.ARRAY(sa.UUID()), nullable=True))
    op.create_index('idx_events_categories_gin', 'events', ['categories'], unique=False, postgresql_using='gin')
    op.create_index('idx_events_series_ids_gin', 'events', ['series_ids'], unique=False, postgresql_using='gin')
    op.create_index('idx_events_tags_gin', 'events', ['tags'], unique=False, postgresql_using='gin')
    op.drop_constraint(op.f('events_series_id_fkey'), 'events', type_='foreignkey')
    op.drop_column('events', 'series_id')
    op.drop_column('events', 'tag_ids')
    op.drop_column('events', 'category')
    op.drop_column('events', 'category_ids')
    op.add_column('series', sa.Column('categories', postgresql.ARRAY(sa.String()), nullable=True))
    # JSONB→text[] can't be done via ALTER COLUMN USING (no subqueries allowed)
    # Use add/update/drop/rename approach instead
    op.add_column('series', sa.Column('tags_new', postgresql.ARRAY(sa.String()), nullable=True))
    op.execute("UPDATE series SET tags_new = ARRAY(SELECT jsonb_array_elements_text(tags)) WHERE tags IS NOT NULL")
    op.drop_column('series', 'tags')
    op.alter_column('series', 'tags_new', new_column_name='tags')
    op.create_index('idx_series_categories_gin', 'series', ['categories'], unique=False, postgresql_using='gin')
    op.create_index('idx_series_tags_gin', 'series', ['tags'], unique=False, postgresql_using='gin')
    op.drop_column('series', 'category')
    op.drop_column('series', 'category_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('category_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.add_column('series', sa.Column('category', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index('idx_series_tags_gin', table_name='series', postgresql_using='gin')
    op.drop_index('idx_series_categories_gin', table_name='series', postgresql_using='gin')
    op.alter_column('series', 'tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('series', 'categories')
    op.add_column('events', sa.Column('category_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('tag_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True))
    op.add_column('events', sa.Column('series_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('events_series_id_fkey'), 'events', 'series', ['series_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_events_tags_gin', table_name='events', postgresql_using='gin')
    op.drop_index('idx_events_series_ids_gin', table_name='events', postgresql_using='gin')
    op.drop_index('idx_events_categories_gin', table_name='events', postgresql_using='gin')
    op.drop_column('events', 'series_ids')
    op.drop_column('events', 'tags')
    op.drop_column('events', 'categories')
    # ### end Alembic commands ###
